---
- name: confluent-jdbc-connector
  hosts: 127.0.0.1
  connection: local

  vars:
    ansible_become_pass: "lucifer317"

  tasks:
    # Install confluent
    - name: wget -qO - https://packages.confluent.io/deb/4.1/archive.key | sudo apt-key add -
      become: yes
      apt_key:
        url: https://packages.confluent.io/deb/4.1/archive.key
        state: present

    - name: sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/4.1 stable main"
      become: yes
      apt_repository: 
        repo: deb [arch=amd64] https://packages.confluent.io/deb/4.1 stable main
        state: present

    - name: apt-get update
      become: yes
      apt: 
        # upgrade: dist
        update_cache: yes

    - name: Install the confluent-platform
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - confluent-platform-oss-2.11

    # Start confluent
    - name: Start confluent-zookeeper
      become: yes
      shell: systemctl start confluent-zookeeper

    - name: Start confluent-kafka
      become: yes
      shell: systemctl start confluent-kafka

    - name: Start confluent-schema-registry
      become: yes
      shell: systemctl start confluent-schema-registry

    - name: Start confluent-kafka-connect
      become: yes
      shell: systemctl start confluent-kafka-connect

    - name: Start confluent-kafka-rest
      become: yes
      shell: systemctl start confluent-kafka-rest

    - name: Start confluent-ksql
      become: yes
      shell: systemctl start confluent-ksql

    # Install confluent-connect-jdbc
    - name: Download confluent-hub
      get_url: 
        url: http://client.hub.confluent.io/confluent-hub-client-latest.tar.gz
        dest: /home/yungshun/Downloads/confluent-hub-client-latest.tar.gz
        mode: 0440

    - name: Extract confluent-hub file
      become: yes
      unarchive: 
        src: /home/yungshun/Downloads/confluent-hub-client-latest.tar.gz
        dest: /usr/local/confluent-hub
       
    - name: Install pexpect
      become: yes
      pip:
        name: pexpect

    - name: Install kafka-connect-jdbc
      become: yes
      expect:
        echo: yes
        command: "/usr/local/confluent-hub/bin/confluent-hub install confluentinc/kafka-connect-jdbc:5.0.1"
        responses:
          'Do you want to install this into \/usr\/share\/confluent-hub-components\?': 'y'
          'I agree to the software license agreement': 'y'
          'Do you want to uninstall existing version 5.0.1\?': 'N'
          'Do you want to update all detected configs\?': 'y'
      ignore_errors: yes
      register: install_kafka_connect_jdbc

    - name: Debug install_kafka_connect_jdbc
      debug: 
        var: install_kafka_connect_jdbc

    # Start the connector
    #- name: Create topics
    #  become: yes
    #  shell: ./bin/kafka-topics --create --zookeeper localhost:2181 --topic connect-configs --replication-factor 3 --partitions 1 --config cleanup.policy=compact
    #  args:
    #    chdir: /usr

    - name: Start the jdbc connector by REST
      shell: "curl -X POST -H \"Content-Type: application/json\" --data \'{\"name\": \"jdbc-sink\", \"config\": {\"connector.class\":\"io.confluent.connect.jdbc.JdbcSinkConnector\",\"tasks.max\":\"1\",\"topics\":\"orders\",\"connection.url\":\"jdbc:postgresql://localhost:5432/yungshun\",\"connection.user\":\"yungshun\",\"connection.password\":\"lucifer317\",\"auto.create\":\"true\",\"name\":\"jdbc-sink\"}}\' http://localhost:8083/connectors"
      register: start_jdbc_sink

    - name: Debug start_jdbc_sink
      debug:
        var: start_jdbc_sink

    - name: Get the connector status
      shell: curl -s -X GET http://localhost:8083/connectors/jdbc-sink/status
      register: get_jdbc_sink_status

    - name: Debug get_jdbc_sink_status
      debug:
        var: get_jdbc_sink_status

    - name: Delete the connector
      shell: curl -X DELETE http://localhost:8083/connectors/jdbc-sink
      register: delete_jdbc_sink

    - name: Debug delete_jdbc_sink
      debug:
        var: delete_jdbc_sink
