---
- name: confluent-jdbc-connector
  hosts: 127.0.0.1
  connection: local

  vars:
    ansible_become_pass: "lucifer317"

  tasks:
    # Install confluent
    - name: wget -qO - https://packages.confluent.io/deb/4.1/archive.key | sudo apt-key add -
      become: yes
      apt_key:
        url: https://packages.confluent.io/deb/4.1/archive.key
        state: present

    - name: sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/4.1 stable main"
      become: yes
      apt_repository: 
        repo: deb [arch=amd64] https://packages.confluent.io/deb/4.1 stable main
        state: present

    - name: apt-get update
      become: yes
      apt: 
        # upgrade: dist
        update_cache: yes

    - name: Install the confluent-platform
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - confluent-platform-oss-2.11

    # Start confluent
    - name: Start confluent-zookeeper
      become: yes
      shell: systemctl start confluent-zookeeper

    - name: Start confluent-kafka
      become: yes
      shell: systemctl start confluent-kafka

    - name: Start confluent-schema-registry
      become: yes
      shell: systemctl start confluent-schema-registry

    - name: Start confluent-kafka-connect
      become: yes
      shell: systemctl start confluent-kafka-connect

    - name: Start confluent-kafka-rest
      become: yes
      shell: systemctl start confluent-kafka-rest

    - name: Start confluent-ksql
      become: yes
      shell: systemctl start confluent-ksql

