---
- name: confluent-jdbc-connector
  hosts: 127.0.0.1
  connection: local

  vars:
    ansible_become_pass: "lucifer317"

  tasks:
    # Install confluent
    - name: wget -qO - https://packages.confluent.io/deb/4.1/archive.key | sudo apt-key add -
      become: yes
      apt_key:
        url: https://packages.confluent.io/deb/4.1/archive.key
        state: present

    - name: sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/4.1 stable main"
      become: yes
      apt_repository: 
        repo: deb [arch=amd64] https://packages.confluent.io/deb/4.1 stable main
        state: present

    - 
